name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password123!
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password123! -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore tools
      run: dotnet tool restore
      
    - name: Build and test (core tests)
      run: dotnet cake --target=TestAllExcludingReadonly
      
    - name: Set up SQL Server connection for readonly tests
      run: |
        cd src/Highway.Data.ReadonlyTests
        dotnet user-secrets set "SqlConnectionString" "Server=localhost,1433;Database=master;User ID=sa;Password=Password123!;TrustServerCertificate=true;"
        cd ../..
    
    - name: Install SQL command line tools
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        
    - name: Test readonly tests with SQL Server
      run: |
        export PATH="$PATH:/opt/mssql-tools/bin"
        # Test if SQL Server is available
        if sqlcmd -S localhost,1433 -U sa -P Password123! -Q "SELECT 1" > /dev/null 2>&1; then
          echo "SQL Server is available, running readonly tests"
          dotnet test src/Highway.Data.ReadonlyTests/Highway.Data.ReadonlyTests.csproj --configuration Debug
        else
          echo "SQL Server not available, skipping readonly tests"
        fi
      continue-on-error: true